### ISSUE TITLE
Map not asking for location access

### ISSUE THREAD

**Issue by Shifs** [nickcoury/nativescript-maps-app#7] opened 2017-09-05 10:06 UTC
I am using this library . Initially it was asking for location. But since few days I found that it is not asking for location . I have used this in my application and without location I cannot plot the map

**Comment by nickcoury** [comment] 2017-09-05 17:16
This repo is only a basic example of getting going with Google Maps on Nativescript.  It should ask for location on first load, but its quite possible (and likely) that if a user declines location access or changes the setting later that it won't re-ask for location permissions.  If you need logic to detect that location permissions have been disabled, that may be up to you to write logic to fix.

Can you provide more details of what is happening?  Is the location permission specifically disabled in the settings, and did you deny the permission when loading the app? Did you try removing the app from your phone completely, rebuilding it cleanly, and redeploying it? With a fresh slate like that does it still not prompt for location?

If there is a bug (as opposed to an unimplemented feature), can you tell if it is in this sample app, or the `nativescript-google-maps-sdk` plugin? If it is the latter, you likely need to raise the issue in that repo.  If the issue is a feature you'd like to see in this project but isn't implemented, you're welcome to submit a Pull Request with the feature added, that way others can also take advantage of it.

**Comment by nickcoury** [comment] 2017-10-05 17:47
Closing. If this is a bug in this repo's code (and not just a feature request), please reopen with more details.  If it is a feature request, please submit a PR with the desired feature implemented.

**Closed as completed by nickcoury** 2017-10-05 17:47 UTC
